# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
  
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
        
  job1:
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v3
       - name: Set up Python 3.10
         uses: actions/setup-python@v3
         with:
            python-version: "3.10" 

  job2:
       needs: job1
       runs-on: ubuntu-latest   
       steps:
           - name: Install Poetry Action
             uses: snok/install-poetry@v1.3.4
             with:
                virtualenvs-create: true
                virtualenvs-in-project: false
                installer-parallel: true
  job3:
      needs: [job1, job2]
      runs-on: ubuntu-latest
      steps:
      - name: Install dep
        run: |
              poetry install --no-root
  job4:
      needs: job3
      runs-on: ubuntu-latest
      steps:
        - name: Poetry Test 
          run: |
               poetry run task test
  job5: 
      needs: job4  
      runs-on: ubuntu-latest
      steps:
       - name: Poetry lint 
         run: |
              poetry run task lint 
  job6:
      needs: job5
      runs-on: ubuntu-latest  
      steps:
       - name: Poetry fromatter 
         run: |
              poetry run task formatter
  job7:
      needs: job6
      runs-on: ubuntu-latest
      steps:
      - name: Poetry security  
        run: |
             poetry run task security   
    
  

        
         
